# Generated by Django 2.0.7 on 2019-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='会议名称')),
                ('meeting_startdate', models.DateTimeField(blank=True, null=True, verbose_name='会议开始时间')),
                ('meeting_finishdate', models.DateTimeField(blank=True, null=True, verbose_name='会议结束时间')),
                ('signup_startdate', models.DateTimeField(blank=True, null=True, verbose_name='报名开始时间')),
                ('signup_finishdate', models.DateTimeField(blank=True, null=True, verbose_name='报名结束时间')),
                ('venue', models.TextField(blank=True, null=True, verbose_name='举办地点')),
                ('organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='主办单位')),
                ('co_organizer', models.CharField(blank=True, max_length=255, null=True, verbose_name='协办单位')),
                ('content', models.TextField(blank=True, null=True, verbose_name='会议内容')),
                ('adddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'db_table': 'meeting_info',
            },
        ),
        migrations.CreateModel(
            name='MeetingLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField(blank=True, null=True, verbose_name='logo')),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_by_meeting', to='app_meeting.Meeting')),
            ],
            options={
                'db_table': 'meeting_logo',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('phonenumber', models.CharField(max_length=30, verbose_name='手机号')),
                ('signupdate', models.DateTimeField(blank=True, null=True, verbose_name='报名时间')),
                ('arrivedate', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_by_meeting', to='app_meeting.Meeting')),
            ],
            options={
                'db_table': 'meeting_participants',
            },
        ),
    ]
