# Generated by Django 2.0.7 on 2019-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='生源地'),
        ),
        migrations.AddField(
            model_name='user',
            name='nation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='民族'),
        ),
    ]
